version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    environmet:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumens:
      # Default path to mongo db. I've mounted it
      - my-mongo-data:/data/db
  mongo-express:
    image: mongo-express
    # If it fails, I'll restart 
    restart: always 
    ports:
      - "8081:8081" 
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  my-mongo-data:
    drive: local
